# Generated by Django 5.2 on 2025-05-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesdiseaseapp', '0002_diabetesrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='BMI',
            new_name='blood_pressure',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='BloodPressure',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='DiabetesPedigreeFunction',
            new_name='diabetes_pedigree_function',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='Glucose',
            new_name='glucose',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='Insulin',
            new_name='insulin',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='Pregnancies',
            new_name='pregnancies',
        ),
        migrations.RenameField(
            model_name='diabetesrecord',
            old_name='SkinThickness',
            new_name='skin_thickness',
        ),
    ]
