# Generated by Django 5.2 on 2025-05-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesdiseaseapp', '0003_rename_age_diabetesrecord_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Fasting', 'Fasting'), ('Postprandial', 'Postprandial')], max_length=20)),
                ('glucose_level', models.FloatField()),
                ('mood', models.CharField(blank=True, choices=[('good', '😊 Good'), ('okay', '😐 Okay'), ('tired', '😞 Tired')], max_length=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
